In [3]:
import numpy as np

In [5]:
a1 = np.array([1,2,3]) #one dimensional array
print(a1)
print(a1.shape)
print(a1.size)
print(a1.ndim)

[1 2 3]
(3,)
3
1


In [14]:
ex1 = np.array([[1,2,3],[4,5,6]])
print(ex1)
print(ex1.ndim)
print(ex1.size)
print(ex1.shape)


[[1 2 3]
 [4 5 6]]
2
6
(2, 3)


In [29]:
a2  = np.array([[1,2,3],
               [4,5,6]]) 
print(a2)
print(a2.shape)
print(a2.size)


[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [15]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9],
                [67,89,99]],
              [[10,11,12],
               [13,14,15],
               [16,17,18],
               [19,20,21]]])
              
print(a3)
print(a3.shape)
print(a3.size)
print(a3.ndim)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [67 89 99]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]
  [19 20 21]]]
(2, 4, 3)
24
3


In [46]:
a4 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]]
])
print(a4)
print(a4.shape)
print(a4.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)
3


In [43]:
a4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [51]:
import pandas as pd
a5 = pd.DataFrame(a2)
a5

0  1  2
0  1  2  3
1  4  5  6

In [52]:
print(a5)

   0  1  2
0  1  2  3
1  4  5  6


In [59]:
#creating a array of ones and zeros
sample_array = np.ones((2,3))
print(sample_array.dtype)
print(sample_array)
print(sample_array.ndim)
print(type(sample_array))
print(sample_array.shape)

float64
[[1. 1. 1.]
 [1. 1. 1.]]
2
<class 'numpy.ndarray'>
(2, 3)


In [19]:
exp2 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
print(exp2.shape)
print(exp2.ndim)
print(exp2.size)

(1, 3, 3)
3
9
