In [3]:
import numpy as np

In [2]:
a1 = np.array([1,2,3]) #one dimensional array
print(a1)
print(a1.shape)
print(a1.size)
print(a1.ndim)

[1 2 3]
(3,)
3
1


In [3]:
ex1 = np.array([[1,2,3],[4,5,6]])
print(ex1)
print(ex1.ndim)
print(ex1.size)
print(ex1.shape)


[[1 2 3]
 [4 5 6]]
2
6
(2, 3)


In [4]:
a2  = np.array([[1,2,3],
               [4,5,6]]) 
print(a2)
print(a2.shape)
print(a2.size)


[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [5]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9],
                [67,89,99]],
              [[10,11,12],
               [13,14,15],
               [16,17,18],
               [19,20,21]]])
              
print(a3)
print(a3.shape)
print(a3.size)
print(a3.ndim)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [67 89 99]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]
  [19 20 21]]]
(2, 4, 3)
24
3


In [6]:
a4 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]]
])
print(a4)
print(a4.shape)
print(a4.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)
3


In [7]:
a4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
import pandas as pd
a5 = pd.DataFrame(a2)
a5

0  1  2
0  1  2  3
1  4  5  6

In [9]:
print(a5)

   0  1  2
0  1  2  3
1  4  5  6


In [10]:
#creating a array of ones and zeros
sample_array = np.ones((2,3))
print(sample_array.dtype)
print(sample_array)
print(sample_array.ndim)
print(type(sample_array))
print(sample_array.shape)

float64
[[1. 1. 1.]
 [1. 1. 1.]]
2
<class 'numpy.ndarray'>
(2, 3)


In [11]:
exp2 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
print(exp2.shape)
print(exp2.ndim)
print(exp2.size)

(1, 3, 3)
3
9


In [2]:
import numpy as np

In [4]:
#creating  a array of ones and zeros
one = np.ones((1,5))
print(one)

[[1. 1. 1. 1. 1.]]


In [6]:
#2d
d20 = np.ones((2,3))
print(d20)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#for creating three domensional array
d30 = np.ones((3,3))
print(d30)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
import random 

In [24]:
exp4 = np.random.randint(1,10,size = (3,5))
print(exp4)

[[7 2 4 6 5]
 [5 2 2 1 4]
 [4 4 1 6 4]]


In [ ]:
#numpy youtube

In [ ]:
#CREATING AN EMPTY ARRAY

In [14]:
emp = np.empty(4)
print(emp)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.33511290e-306]


In [ ]:
#to arrange the element 

In [16]:
exp5 = np.arange(10)
print(exp5)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#linspace and diognal element used in python


In [25]:
#for creating a diognal matrix
exp8 = np.eye(3,3) #retrun only 2d array
print(exp8.ndim)
print(exp8)

2
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
exp9 =np.eye(3,3,1) # we can change the diognal to be in first second and the third row
print(exp9.ndim)
print(exp9)

2
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [48]:
exp10 =np.eye(3,3,-1) # we can change the diognal to be in first second and the third row
print(exp10.ndim)
print(exp10)

2
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [54]:
exp11 =np.eye(3,3,-2) # we can change the diognal to be in first second and the third row in lower rows using the index elemnt
print(exp11.ndim)
print(exp11)

2
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [ ]:
#creating a random value in numpy
#using the import function for random use

In [55]:
import random

In [59]:
n1 = np.random.rand((10)) # return the positive value between 0 and 1
print(n1) #creating a one dimensional array

[0.26305485 0.95442823 0.53534499 0.67036195 0.07385869 0.51030102
 0.77787876 0.04745519 0.47714716 0.53915139]


In [80]:
n2 = np.random.rand(2,3) #the (2,3) indicates the size of the matrix
n2

array([[0.23292179, 0.82037845, 0.0406688 ],
       [0.67497678, 0.09834379, 0.45032276]])

In [84]:
n2 = np.random.rand(3,3,3) #the (2,3) indicates the size of the matrix
print(n2)
n2.ndim

[[[0.64647943 0.68296422 0.81713899]
  [0.50600034 0.40593404 0.86893914]
  [0.91288542 0.21182832 0.61620485]]

 [[0.34077513 0.48713579 0.67405191]
  [0.35369642 0.76126885 0.44492232]
  [0.71011127 0.18888896 0.70429885]]

 [[0.32531727 0.18060915 0.49694036]
  [0.26519844 0.33563804 0.93094494]
  [0.27770615 0.44461342 0.45297526]]]


3

In [97]:
#using the randn
n2 = np.random.randn(1)  # the 1 indicates the the dimensional of the array created and the randn retrurn the valaue positive and negative
n2

array([-0.00219199])

In [101]:
n2 = np.random.randn(2,3)  # the 1 indicates the the dimensional of the array created and the randn retrurn the valaue positive and negative
print(n2)
n2.ndim

[[ 0.49188684  0.3826841  -0.77466747]
 [ 1.23350968  1.50882567 -0.33589265]]


2

In [103]:
n2 = np.random.randn(3,2,3)  # the 1 indicates the the dimensional of the array created and the randn retrurn the valaue positive and negative
print(n2)
n2.ndim

[[[ 0.53462856 -0.30487048 -1.04833719]
  [ 0.40348055  0.30359841 -0.88203825]]

 [[ 0.89249468  0.07369736  0.3445285 ]
  [ 1.62033851 -1.41650358  0.03743037]]

 [[ 2.82617832 -0.22673382  0.2089018 ]
  [-2.79542618  0.86555164 -0.2505538 ]]]


3

In [112]:
random.sample(range(10000000),10)

[324072,
 2828876,
 2502904,
 7660966,
 9024722,
 6679001,
 8579068,
 3982459,
 6929774,
 6904247]

In [114]:
random.sample(['red', 'blue'], counts=[4, 2], k=5)

['red', 'blue', 'red', 'blue', 'red']

In [ ]:
#to use the ranint


In [137]:
n2 = np.random.randint(0,10,size = (3,3,3))  # the 1 indicates the the dimensional of the array created and the randn retrurn the valaue positive and negative
print(n2)


[[[3 2 5]
  [8 5 2]
  [3 5 0]]

 [[1 7 1]
  [6 1 6]
  [1 6 2]]

 [[6 8 0]
  [5 1 4]
  [7 0 5]]]


In [ ]:
#data type in numpy array

In [ ]:
#converting from one datatype to another datatype

In [139]:
np1 = np.array([1,2,3,4],dtype="f")
print(np1)

[1. 2. 3. 4.]


In [6]:
#shape in numpy array
sh1 = np.array([1,2,3,4,5])
np.shape(sh1)

(5,)

In [8]:
sh2 = np.random.randint(1,10,size = (3,3))
np.shape(sh2)

(3, 3)

#reshape

In [18]:
sh3 = np.random.randint(1,10,(3,3))
x1 = sh3.reshape(2,3) #this cannot be done from 2d to 3d only one dimesional to another dimensional is possibel

ValueError: cannot reshape array of size 9 into shape (2,3)

In [42]:
sh4 =np.random.rand(110)
print(sh4)
sh4.ndim

print("now concverting the 1d to array to other arrays")
x = sh4.reshape(1,110)

[1.87681343e-01 4.70510760e-01 4.40327478e-01 2.32047770e-01
 6.90627813e-01 7.57805389e-01 5.61470672e-03 7.12765448e-01
 5.73674244e-01 8.73330190e-01 5.57623378e-01 4.89197608e-02
 5.17483896e-01 8.58733485e-01 1.49505402e-01 9.27199092e-01
 9.01533528e-01 5.62323249e-02 8.27019277e-01 7.40712648e-01
 1.09764825e-01 7.02718561e-02 3.86514558e-01 4.43855538e-02
 9.37693946e-01 3.01180552e-01 6.78803635e-01 3.84592968e-01
 5.36302600e-01 9.76639397e-01 7.17885978e-01 4.94012342e-01
 8.26305877e-01 6.07630548e-01 6.94677713e-01 6.24161735e-01
 7.20539151e-01 9.23410669e-01 4.26717304e-01 7.22318813e-01
 5.13184855e-01 9.08351540e-01 6.23779078e-01 5.56390648e-01
 3.10276858e-01 5.96027593e-01 4.22361046e-01 1.19488496e-01
 4.57560086e-01 3.44131880e-01 1.42373555e-01 3.28040563e-01
 6.46235341e-01 2.36983332e-01 7.22259736e-01 4.38188770e-01
 2.45245340e-02 7.39674543e-01 4.83201176e-01 2.41140337e-01
 7.00571082e-01 2.58588218e-01 8.31453539e-02 5.71694441e-01
 2.74049465e-01 7.925660

In [48]:
sh5 = np.array([1,2,3,4,5,6,7,8,9])
x1 = sh5.reshape(3,3)
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
class hello():

    def __init__(self,name,age) -> None:
        self.name = name
        self.age = age
    def __str__(self) -> str:
        print(f"hello my name is {self.name} and my age is {self.age}")

obj1 = hello("neeraj",18)
obj1.__str__()
        

hello my name is neeraj and my age is 18


In [1]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [1]:
def square(num):
    ans = num*num

    return ans

k = int(input("please enter the number that you want to find the sqyuare"))
square(k)

100

In [13]:
def reverse(y):
    for i in range(len(y)):
        s = y[i] + " "
    print(s)

l = input("Enter the name of the text:")
reverse(l)

o 


In [9]:
v = "hello"
for i in range(len(v)):
    print(v[i])

h
e
l
l
o


In [1]:
import tkinter as tk
from math import *

def calculate():
    expression = entry.get()
    try:
        result = eval(expression)
        entry.delete(0, tk.END)
        entry.insert(tk.END, result)
    except:
        entry.delete(0, tk.END)
        entry.insert(tk.END, "Error")

root = tk.Tk()
root.title("Scientific Calculator")

entry = tk.Entry(root, width=35, borderwidth=5)
entry.grid(row=0, column=0, columnspan=4, padx=10, pady=10)

button_frame = tk.Frame(root)
button_frame.grid(row=1, column=0, columnspan=4)

# Create buttons for digits and operators
button_list = [
    "7", "8", "9", "+",
    "4", "5", "6", "-",
    "1", "2", "3", "*",
    ".", "0", "C", "/"
]

# Create buttons and add them to the button frame
for i in range(16):
    button = tk.Button(button_frame, text=button_list[i], width=5, height=2)
    button.grid(row=i // 4, column=i % 4)

# Create the equal button
equal_button = tk.Button(root, text="=", width=5, height=2, command=calculate)
equal_button.grid(row=5, column=3, pady=10)

root.mainloop()


In [1]:
import math

def calc():
  while True:
    try:
      operation = input("Enter operation (q to quit): ")
      if operation == 'q':
        break
      num1 = float(input("Enter first number: "))
      num2 = float(input("Enter second number: "))
      if operation == '+':
        print("Result: ", num1 + num2)
      elif operation == '-':
        print("Result: ", num1 - num2)
      elif operation == '*':
        print("Result: ", num1 * num2)
      elif operation == '/':
        print("Result: ", num1 / num2)
      elif operation == '^':
        print("Result: ", num1 ** num2)
      elif operation == 'sin':
        print("Result: ", math.sin(num1))
      elif operation == 'cos':
        print("Result: ", math.cos(num1))
      elif operation == 'tan':
        print("Result: ", math.tan(num1))
      elif operation == 'log':
        print("Result: ", math.log(num1, num2))
      else:
        print("Invalid operator, try again.")
    except ValueError:
      print("Invalid input, try again.")

if __name__ == '__main__':
  calc()


KeyboardInterrupt: Interrupted by user